### 댓글 작성
POST http://localhost:8080/performances/1/comments
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json

{
  "title" : "믿고듣는아이유3",
  "description" : "앵앵콜ㅜㅜ짱",
  "rate": 5
}

### 댓글 삭제
DELETE http://localhost:8080/performances/1/comments/1
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json


### 단일 공연 댓글 조회
GET http://localhost:8080/performances/1/comments
Content-Type: application/json
