### 댓글 작성
POST http://localhost:8080/performances/1/comments
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json

{
  "title" : "믿고듣는아이유",
  "description" : "앵앵콜ㅜㅜㅜ짱",
  "rate": 1
}

### 댓글 삭제
DELETE http://localhost:8080/performances/1/comments/1
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json
