### 관심 공연 등록
POST http://localhost:8080/performances/1/likes
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}


### 관심 공연 등록 취소
DELETE http://localhost:8080/performances/1/likes/1
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}


### 관심 개수 조회
GET http://localhost:8080/performances/1/likes-count
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}


### 관심 공연 등록 여부 조회
GET http://localhost:8080/performances/1/likes
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}