### 결제 완료
POST http://localhost:8080/sessions/1/orders
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json

{
  "seatIdList":  [5, 6],
  "modifiedAt" : "2024-08-14-20:29"
}

### 예매 내역 조회
GET http://localhost:8080/users/1/orders
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}

### 예매 취소
PATCH http://localhost:8080/users/orders/1
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}