### 결제 완료
POST http://localhost:8080/sessions/1/orders
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}
Content-Type: application/json

{
  "seatIdList":  [3]
}

### 예매 내역 조회
GET http://localhost:8080/users/1/orders
Authorization: {{Authorization}}
RefreshToken: {{RefreshToken}}